
version: 0.2

phases:
  pre_build:
    commands:
      - echo Install packages...
      - npm install
  build:
    commands:
      - eb setenv NODE_ENV=production
      - echo Create build...
      - npm run build
  post_build:
    commands:
      - echo Removing unnecessary files...
